create database customer_behavior;
use customer_behavior;

-- Q1. What is the total revenue generated by male vs. female customers?

select gender, sum(purchase_amount) as revenue
from customer
group by gender;

-- Q2. Which customers used a discount but still spent more than the average purchase amount? 
select customer_id, discount_applied, purchase_amount
from customer 
where discount_applied='Yes'
and purchase_amount > (select avg(purchase_amount) from customer);

-- Q3. Which are the top 5 products with the highest average review rating?
select item_purchased, round(avg(review_rating),2) as Avg_rating
from customer 
group by item_purchased 
order by Avg_rating desc
limit 5;

-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
select shipping_type, round(avg(purchase_amount),2) as Amount
from customer 
group by shipping_type
having shipping_type = 'Express' or shipping_type = 'Standard';

-- Q5. Do subscribed customers spend more? Compare average spend and total revenue 
select subscription_status, 
count(customer_id) as total_customers, 
round(avg(purchase_amount),2) as Avg_spend, 
round(sum(purchase_amount),2) as Total_revenue
from customer
group by subscription_status
order by Avg_spend, Total_revenue desc;

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
select item_purchased, 
round(100.0 * sum(case
	when discount_applied = 'Yes' then 1 else 0 end)/count(*),2) as discount_rate
from customer
group by item_purchased
order by discount_rate desc
limit 5;

-- Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment. 
with customer_type as(
select customer_id, previous_purchases,
case 
	when previous_purchases = 1 then 'New'
    when previous_purchases between 2 and 10 then 'Returning'
    else 'Loyal'
    end as customer_segment
from customer
)

select customer_segment, count(*) as "Number of Customers"
from customer_type
group by customer_segment;

-- Q8. What are the top 3 most purchased products within each category? 
with item_counts as(
	select category, item_purchased, count(customer_id) as total_orders,
    rank() over(partition by category order by count(customer_id)desc) as item_rank
    from customer
    group by category, item_purchased
) 
select category, item_purchased, total_orders
from item_counts
where item_rank <= 3;

-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe
with repeat_buyers as (
select previous_purchases, subscription_status
from customer 
where previous_purchases > 5
)
select subscription_status, count(previous_purchases) as repeat_buyers
from repeat_buyers
group by subscription_status
order by repeat_buyers;

-- Q10. What is the revenue contribution of each age group? 
select age_group, round(100.0*sum(purchase_amount)/(select sum(purchase_amount) from customer),2) as total_revenue
from customer
group by age_group
order by total_revenue desc;


